import type { ComponentDefinition } from '@/types';

export const COMPONENT_LIBRARY: ComponentDefinition[] = [
  {
    type: 'arduino-uno',
    label: 'Arduino Uno',
    category: 'Microcontrollers',
    description: 'Arduino Uno Rev3 — ATmega328P microcontroller with 14 digital pins and 6 analog inputs.',
    width: 280,
    height: 200,
    keywords: ['arduino', 'uno', 'microcontroller', 'mcu', 'board'],
    pins: [
      // Digital pins (top row)
      { id: 'd0', name: 'D0', type: 'serial', x: 40, y: 0, label: 'RX' },
      { id: 'd1', name: 'D1', type: 'serial', x: 60, y: 0, label: 'TX' },
      { id: 'd2', name: 'D2', type: 'digital', x: 80, y: 0 },
      { id: 'd3', name: 'D3', type: 'pwm', x: 100, y: 0 },
      { id: 'd4', name: 'D4', type: 'digital', x: 120, y: 0 },
      { id: 'd5', name: 'D5', type: 'pwm', x: 140, y: 0 },
      { id: 'd6', name: 'D6', type: 'pwm', x: 160, y: 0 },
      { id: 'd7', name: 'D7', type: 'digital', x: 180, y: 0 },
      { id: 'd8', name: 'D8', type: 'digital', x: 200, y: 0 },
      { id: 'd9', name: 'D9', type: 'pwm', x: 220, y: 0 },
      { id: 'd10', name: 'D10', type: 'pwm', x: 240, y: 0 },
      { id: 'd11', name: 'D11', type: 'pwm', x: 260, y: 0 },
      { id: 'd12', name: 'D12', type: 'digital', x: 280, y: 0 },
      { id: 'd13', name: 'D13', type: 'digital', x: 300, y: 0 },
      // GND (top-right)
      { id: 'gnd1', name: 'GND', type: 'ground', x: 320, y: 0 },
      // AREF
      { id: 'aref', name: 'AREF', type: 'analog', x: 340, y: 0 },
      // Analog pins (bottom row)
      { id: 'a0', name: 'A0', type: 'analog', x: 40, y: 200 },
      { id: 'a1', name: 'A1', type: 'analog', x: 60, y: 200 },
      { id: 'a2', name: 'A2', type: 'analog', x: 80, y: 200 },
      { id: 'a3', name: 'A3', type: 'analog', x: 100, y: 200 },
      { id: 'a4', name: 'A4', type: 'analog', x: 120, y: 200 },
      { id: 'a5', name: 'A5', type: 'analog', x: 140, y: 200 },
      // Power pins (bottom-right)
      { id: 'vin', name: 'VIN', type: 'power', x: 200, y: 200 },
      { id: 'gnd2', name: 'GND', type: 'ground', x: 220, y: 200 },
      { id: 'gnd3', name: 'GND', type: 'ground', x: 240, y: 200 },
      { id: '5v', name: '5V', type: 'power', x: 260, y: 200 },
      { id: '3v3', name: '3.3V', type: 'power', x: 280, y: 200 },
      { id: 'rst', name: 'RST', type: 'digital', x: 300, y: 200 },
    ],
    defaultProps: {},
  },
  {
    type: 'arduino-nano',
    label: 'Arduino Nano',
    category: 'Microcontrollers',
    description: 'Arduino Nano — compact ATmega328P board with mini-USB.',
    width: 160,
    height: 220,
    keywords: ['arduino', 'nano', 'microcontroller', 'mcu', 'small'],
    pins: [
      { id: 'd13', name: 'D13', type: 'digital', x: 0, y: 20 },
      { id: '3v3', name: '3.3V', type: 'power', x: 0, y: 40 },
      { id: 'aref', name: 'AREF', type: 'analog', x: 0, y: 60 },
      { id: 'a0', name: 'A0', type: 'analog', x: 0, y: 80 },
      { id: 'a1', name: 'A1', type: 'analog', x: 0, y: 100 },
      { id: 'a2', name: 'A2', type: 'analog', x: 0, y: 120 },
      { id: 'a3', name: 'A3', type: 'analog', x: 0, y: 140 },
      { id: 'a4', name: 'A4', type: 'analog', x: 0, y: 160 },
      { id: 'a5', name: 'A5', type: 'analog', x: 0, y: 180 },
      { id: 'a6', name: 'A6', type: 'analog', x: 0, y: 200 },
      { id: 'a7', name: 'A7', type: 'analog', x: 0, y: 220 },
      { id: '5v', name: '5V', type: 'power', x: 160, y: 20 },
      { id: 'rst', name: 'RST', type: 'digital', x: 160, y: 40 },
      { id: 'gnd', name: 'GND', type: 'ground', x: 160, y: 60 },
      { id: 'd7', name: 'D7', type: 'digital', x: 160, y: 80 },
      { id: 'd6', name: 'D6', type: 'pwm', x: 160, y: 100 },
      { id: 'd5', name: 'D5', type: 'pwm', x: 160, y: 120 },
      { id: 'd4', name: 'D4', type: 'digital', x: 160, y: 140 },
      { id: 'd3', name: 'D3', type: 'pwm', x: 160, y: 160 },
      { id: 'd2', name: 'D2', type: 'digital', x: 160, y: 180 },
      { id: 'd1', name: 'D1', type: 'serial', x: 160, y: 200 },
      { id: 'd0', name: 'D0', type: 'serial', x: 160, y: 220 },
    ],
    defaultProps: {},
  },
  {
    type: 'raspberry-pi-pico',
    label: 'Raspberry Pi Pico',
    category: 'Microcontrollers',
    description: 'Raspberry Pi Pico — RP2040 dual-core microcontroller.',
    width: 160,
    height: 200,
    keywords: ['raspberry', 'pi', 'pico', 'rp2040', 'microcontroller'],
    pins: [
      { id: 'gp0', name: 'GP0', type: 'digital', x: 0, y: 20 },
      { id: 'gp1', name: 'GP1', type: 'digital', x: 0, y: 40 },
      { id: 'gnd1', name: 'GND', type: 'ground', x: 0, y: 60 },
      { id: 'gp2', name: 'GP2', type: 'digital', x: 0, y: 80 },
      { id: 'gp3', name: 'GP3', type: 'digital', x: 0, y: 100 },
      { id: 'gp4', name: 'GP4', type: 'digital', x: 0, y: 120 },
      { id: 'gp5', name: 'GP5', type: 'digital', x: 0, y: 140 },
      { id: 'gnd2', name: 'GND', type: 'ground', x: 0, y: 160 },
      { id: 'gp6', name: 'GP6', type: 'pwm', x: 0, y: 180 },
      { id: 'gp7', name: 'GP7', type: 'digital', x: 0, y: 200 },
      { id: '3v3', name: '3V3', type: 'power', x: 160, y: 20 },
      { id: 'gnd3', name: 'GND', type: 'ground', x: 160, y: 40 },
      { id: 'gp8', name: 'GP8', type: 'pwm', x: 160, y: 60 },
      { id: 'gp9', name: 'GP9', type: 'pwm', x: 160, y: 80 },
      { id: 'gnd4', name: 'GND', type: 'ground', x: 160, y: 100 },
      { id: 'gp10', name: 'GP10', type: 'pwm', x: 160, y: 120 },
      { id: 'gp11', name: 'GP11', type: 'pwm', x: 160, y: 140 },
      { id: 'gnd5', name: 'GND', type: 'ground', x: 160, y: 160 },
      { id: 'gp12', name: 'GP12', type: 'pwm', x: 160, y: 180 },
      { id: 'gp13', name: 'GP13', type: 'pwm', x: 160, y: 200 },
    ],
    defaultProps: {},
  },
  {
    type: 'esp32',
    label: 'ESP32',
    category: 'Microcontrollers',
    description: 'ESP32 DevKit — WiFi/Bluetooth dual-core microcontroller.',
    width: 180,
    height: 240,
    keywords: ['esp32', 'wifi', 'bluetooth', 'microcontroller', 'esp'],
    pins: [
      { id: '3v3', name: '3V3', type: 'power', x: 0, y: 20 },
      { id: 'en', name: 'EN', type: 'digital', x: 0, y: 40 },
      { id: 'gp36', name: 'VP', type: 'analog', x: 0, y: 60 },
      { id: 'gp39', name: 'VN', type: 'analog', x: 0, y: 80 },
      { id: 'gp34', name: 'D34', type: 'analog', x: 0, y: 100 },
      { id: 'gp35', name: 'D35', type: 'analog', x: 0, y: 120 },
      { id: 'gp32', name: 'D32', type: 'analog', x: 0, y: 140 },
      { id: 'gp33', name: 'D33', type: 'analog', x: 0, y: 160 },
      { id: 'gp25', name: 'D25', type: 'pwm', x: 0, y: 180 },
      { id: 'gp26', name: 'D26', type: 'pwm', x: 0, y: 200 },
      { id: 'gp27', name: 'D27', type: 'pwm', x: 0, y: 220 },
      { id: 'gnd', name: 'GND', type: 'ground', x: 0, y: 240 },
      { id: 'gp23', name: 'D23', type: 'digital', x: 180, y: 20 },
      { id: 'gp22', name: 'D22', type: 'digital', x: 180, y: 40 },
      { id: 'gp1', name: 'TX', type: 'serial', x: 180, y: 60 },
      { id: 'gp3', name: 'RX', type: 'serial', x: 180, y: 80 },
      { id: 'gp21', name: 'D21', type: 'digital', x: 180, y: 100 },
      { id: 'gp19', name: 'D19', type: 'digital', x: 180, y: 120 },
      { id: 'gp18', name: 'D18', type: 'digital', x: 180, y: 140 },
      { id: 'gp5', name: 'D5', type: 'digital', x: 180, y: 160 },
      { id: 'gp17', name: 'D17', type: 'digital', x: 180, y: 180 },
      { id: 'gp16', name: 'D16', type: 'digital', x: 180, y: 200 },
      { id: 'gp4', name: 'D4', type: 'digital', x: 180, y: 220 },
      { id: 'gp0', name: 'D0', type: 'digital', x: 180, y: 240 },
    ],
    defaultProps: {},
  },
  {
    type: 'resistor',
    label: 'Resistor',
    category: 'Basic',
    description: 'Resistor — limits current flow. Default 220Ω.',
    width: 100,
    height: 40,
    keywords: ['resistor', 'resistance', 'ohm', 'current', 'limit'],
    pins: [
      { id: 'a', name: 'A', type: 'generic', x: 0, y: 20 },
      { id: 'b', name: 'B', type: 'generic', x: 100, y: 20 },
    ],
    defaultProps: { resistance: 220, label: '220Ω' },
  },
  {
    type: 'capacitor',
    label: 'Capacitor',
    category: 'Basic',
    description: 'Capacitor — stores electrical energy. Default 10µF.',
    width: 80,
    height: 50,
    keywords: ['capacitor', 'capacitance', 'farad', 'filter', 'decoupling'],
    pins: [
      { id: 'a', name: '+', type: 'generic', x: 0, y: 25 },
      { id: 'b', name: '-', type: 'generic', x: 80, y: 25 },
    ],
    defaultProps: { capacitance: 10, label: '10µF' },
  },
  {
    type: 'led',
    label: 'LED',
    category: 'Basic',
    description: 'Light Emitting Diode — emits light when current flows through it.',
    width: 60,
    height: 50,
    keywords: ['led', 'light', 'diode', 'indicator', 'emit'],
    pins: [
      { id: 'a', name: 'Anode', type: 'generic', x: 0, y: 25, label: '+' },
      { id: 'c', name: 'Cathode', type: 'generic', x: 60, y: 25, label: '-' },
    ],
    defaultProps: { color: '#ff3b30', label: 'LED' },
  },
  {
    type: 'rgb-led',
    label: 'RGB LED',
    category: 'Basic',
    description: 'RGB LED — red, green, and blue in one package.',
    width: 60,
    height: 60,
    keywords: ['rgb', 'led', 'color', 'red', 'green', 'blue'],
    pins: [
      { id: 'r', name: 'R', type: 'pwm', x: 0, y: 15, label: 'Red' },
      { id: 'g', name: 'G', type: 'pwm', x: 0, y: 30, label: 'Green' },
      { id: 'b', name: 'B', type: 'pwm', x: 0, y: 45, label: 'Blue' },
      { id: 'c', name: 'GND', type: 'ground', x: 60, y: 30, label: 'Common' },
    ],
    defaultProps: { label: 'RGB LED' },
  },
  {
    type: 'diode',
    label: 'Diode',
    category: 'Basic',
    description: 'Diode — allows current to flow in one direction only.',
    width: 80,
    height: 40,
    keywords: ['diode', 'rectifier', 'one-way'],
    pins: [
      { id: 'a', name: 'Anode', type: 'generic', x: 0, y: 20 },
      { id: 'c', name: 'Cathode', type: 'generic', x: 80, y: 20 },
    ],
    defaultProps: { label: '1N4148' },
  },
  {
    type: 'push-button',
    label: 'Push Button',
    category: 'Inputs',
    description: 'Push button — momentary switch. When pressed, connects its two pins.',
    width: 60,
    height: 60,
    keywords: ['button', 'push', 'switch', 'momentary', 'press', 'input'],
    pins: [
      { id: 'a', name: 'A', type: 'generic', x: 0, y: 20 },
      { id: 'b', name: 'B', type: 'generic', x: 60, y: 20 },
      { id: 'c', name: 'C', type: 'generic', x: 0, y: 40 },
      { id: 'd', name: 'D', type: 'generic', x: 60, y: 40 },
    ],
    defaultProps: { pressed: false, label: 'Button' },
  },
  {
    type: 'switch',
    label: 'Switch',
    category: 'Inputs',
    description: 'Toggle switch — stays in position until switched again.',
    width: 70,
    height: 50,
    keywords: ['switch', 'toggle', 'slide', 'input'],
    pins: [
      { id: 'a', name: 'A', type: 'generic', x: 0, y: 25 },
      { id: 'b', name: 'B', type: 'generic', x: 70, y: 25 },
    ],
    defaultProps: { closed: false, label: 'Switch' },
  },
  {
    type: 'potentiometer',
    label: 'Potentiometer',
    category: 'Inputs',
    description: 'Potentiometer — variable resistor. Outputs 0-5V on the wiper.',
    width: 80,
    height: 80,
    keywords: ['potentiometer', 'pot', 'variable', 'knob', 'analog', 'input'],
    pins: [
      { id: 'a', name: 'VCC', type: 'power', x: 0, y: 20 },
      { id: 'w', name: 'Wiper', type: 'analog', x: 40, y: 80 },
      { id: 'b', name: 'GND', type: 'ground', x: 80, y: 20 },
    ],
    defaultProps: { value: 0.5, label: 'Pot' },
  },
  {
    type: 'buzzer',
    label: 'Buzzer',
    category: 'Outputs',
    description: 'Buzzer — produces a tone when driven with a signal.',
    width: 60,
    height: 60,
    keywords: ['buzzer', 'piezo', 'sound', 'tone', 'output', 'beep'],
    pins: [
      { id: '+', name: '+', type: 'generic', x: 0, y: 30 },
      { id: '-', name: '-', type: 'ground', x: 60, y: 30 },
    ],
    defaultProps: { label: 'Buzzer' },
  },
  {
    type: 'dc-motor',
    label: 'DC Motor',
    category: 'Outputs',
    description: 'DC motor — rotates when voltage is applied. Speed proportional to voltage.',
    width: 80,
    height: 60,
    keywords: ['motor', 'dc', 'rotation', 'spin', 'output'],
    pins: [
      { id: '+', name: '+', type: 'generic', x: 0, y: 30 },
      { id: '-', name: '-', type: 'ground', x: 80, y: 30 },
    ],
    defaultProps: { label: 'Motor' },
  },
  {
    type: 'servo',
    label: 'Servo Motor',
    category: 'Outputs',
    description: 'Servo motor — rotates to a specific angle (0-180°) via PWM signal.',
    width: 80,
    height: 70,
    keywords: ['servo', 'motor', 'angle', 'pwm', 'output', 'robotics'],
    pins: [
      { id: 'sig', name: 'SIG', type: 'pwm', x: 0, y: 20, label: 'Signal' },
      { id: 'vcc', name: 'VCC', type: 'power', x: 0, y: 40, label: '5V' },
      { id: 'gnd', name: 'GND', type: 'ground', x: 0, y: 60, label: 'GND' },
    ],
    defaultProps: { angle: 90, label: 'Servo' },
  },
  {
    type: 'relay',
    label: 'Relay',
    category: 'Outputs',
    description: 'Relay — electrically operated switch. Activated by a control signal.',
    width: 80,
    height: 70,
    keywords: ['relay', 'switch', 'control', 'output'],
    pins: [
      { id: 'sig', name: 'SIG', type: 'digital', x: 0, y: 20 },
      { id: 'vcc', name: 'VCC', type: 'power', x: 0, y: 40 },
      { id: 'gnd', name: 'GND', type: 'ground', x: 0, y: 60 },
      { id: 'com', name: 'COM', type: 'generic', x: 80, y: 25 },
      { id: 'no', name: 'NO', type: 'generic', x: 80, y: 45 },
    ],
    defaultProps: { label: 'Relay' },
  },
  {
    type: 'lcd-16x2',
    label: 'LCD 16x2',
    category: 'Displays',
    description: '16x2 character LCD display. Shows text on 2 lines of 16 characters.',
    width: 220,
    height: 100,
    keywords: ['lcd', 'display', '16x2', 'character', 'text', 'screen'],
    pins: [
      { id: 'vcc', name: 'VCC', type: 'power', x: 0, y: 20 },
      { id: 'gnd', name: 'GND', type: 'ground', x: 0, y: 40 },
      { id: 'rs', name: 'RS', type: 'digital', x: 0, y: 60 },
      { id: 'e', name: 'E', type: 'digital', x: 0, y: 80 },
      { id: 'd4', name: 'D4', type: 'digital', x: 220, y: 20 },
      { id: 'd5', name: 'D5', type: 'digital', x: 220, y: 40 },
      { id: 'd6', name: 'D6', type: 'digital', x: 220, y: 60 },
      { id: 'd7', name: 'D7', type: 'digital', x: 220, y: 80 },
    ],
    defaultProps: { text: 'Hello, World!', label: 'LCD' },
  },
  {
    type: 'oled',
    label: 'OLED Display',
    category: 'Displays',
    description: '0.96" OLED display — 128x64 pixels via I2C.',
    width: 160,
    height: 120,
    keywords: ['oled', 'display', 'i2c', 'screen', 'ssd1306'],
    pins: [
      { id: 'vcc', name: 'VCC', type: 'power', x: 0, y: 30 },
      { id: 'gnd', name: 'GND', type: 'ground', x: 0, y: 60 },
      { id: 'scl', name: 'SCL', type: 'digital', x: 0, y: 90 },
      { id: 'sda', name: 'SDA', type: 'digital', x: 160, y: 90 },
    ],
    defaultProps: { text: 'NEXEL AI', label: 'OLED' },
  },
  {
    type: 'seven-segment',
    label: '7-Segment Display',
    category: 'Displays',
    description: '7-segment display — shows one digit (0-9) via individual segment control.',
    width: 80,
    height: 120,
    keywords: ['seven', 'segment', 'display', 'digit', 'number', '7seg'],
    pins: [
      { id: 'a', name: 'A', type: 'digital', x: 0, y: 10 },
      { id: 'b', name: 'B', type: 'digital', x: 0, y: 25 },
      { id: 'c', name: 'C', type: 'digital', x: 0, y: 40 },
      { id: 'd', name: 'D', type: 'digital', x: 0, y: 55 },
      { id: 'e', name: 'E', type: 'digital', x: 0, y: 70 },
      { id: 'f', name: 'F', type: 'digital', x: 0, y: 85 },
      { id: 'g', name: 'G', type: 'digital', x: 0, y: 100 },
      { id: 'com', name: 'COM', type: 'ground', x: 80, y: 60 },
    ],
    defaultProps: { value: 0, label: '7-Seg' },
  },
  {
    type: 'led-matrix',
    label: 'LED Matrix 8x8',
    category: 'Displays',
    description: '8x8 LED matrix — 64 individually addressable LEDs.',
    width: 120,
    height: 120,
    keywords: ['matrix', 'led', '8x8', 'display', 'grid'],
    pins: [
      { id: 'vcc', name: 'VCC', type: 'power', x: 0, y: 30 },
      { id: 'gnd', name: 'GND', type: 'ground', x: 0, y: 60 },
      { id: 'din', name: 'DIN', type: 'digital', x: 0, y: 90 },
      { id: 'cs', name: 'CS', type: 'digital', x: 120, y: 30 },
      { id: 'clk', name: 'CLK', type: 'digital', x: 120, y: 60 },
    ],
    defaultProps: { label: 'Matrix' },
  },
  {
    type: 'temp-sensor',
    label: 'Temperature Sensor',
    category: 'Sensors',
    description: 'Temperature sensor (LM35) — outputs 10mV/°C analog signal.',
    width: 70,
    height: 70,
    keywords: ['temperature', 'sensor', 'lm35', 'analog', 'thermometer'],
    pins: [
      { id: 'vcc', name: 'VCC', type: 'power', x: 0, y: 20 },
      { id: 'out', name: 'OUT', type: 'analog', x: 0, y: 40 },
      { id: 'gnd', name: 'GND', type: 'ground', x: 0, y: 60 },
    ],
    defaultProps: { temperature: 25, label: 'Temp' },
  },
  {
    type: 'light-sensor',
    label: 'Light Sensor',
    category: 'Sensors',
    description: 'Light-dependent resistor (LDR) — resistance changes with light.',
    width: 70,
    height: 70,
    keywords: ['light', 'sensor', 'ldr', 'photoresistor', 'analog', 'brightness'],
    pins: [
      { id: 'vcc', name: 'VCC', type: 'power', x: 0, y: 20 },
      { id: 'out', name: 'OUT', type: 'analog', x: 0, y: 40 },
      { id: 'gnd', name: 'GND', type: 'ground', x: 0, y: 60 },
    ],
    defaultProps: { light: 0.5, label: 'LDR' },
  },
  {
    type: 'ultrasonic-sensor',
    label: 'Ultrasonic Sensor',
    category: 'Sensors',
    description: 'HC-SR04 ultrasonic distance sensor. Measures distance via echo timing.',
    width: 120,
    height: 80,
    keywords: ['ultrasonic', 'distance', 'hcsr04', 'range', 'sensor'],
    pins: [
      { id: 'vcc', name: 'VCC', type: 'power', x: 0, y: 20 },
      { id: 'trig', name: 'TRIG', type: 'digital', x: 0, y: 40 },
      { id: 'echo', name: 'ECHO', type: 'digital', x: 0, y: 60 },
      { id: 'gnd', name: 'GND', type: 'ground', x: 0, y: 80 },
    ],
    defaultProps: { distance: 100, label: 'Ultrasonic' },
  },
  {
    type: 'pir-sensor',
    label: 'PIR Motion Sensor',
    category: 'Sensors',
    description: 'PIR sensor — detects motion/infrared changes. Outputs HIGH when motion detected.',
    width: 80,
    height: 80,
    keywords: ['pir', 'motion', 'sensor', 'infrared', 'movement'],
    pins: [
      { id: 'vcc', name: 'VCC', type: 'power', x: 0, y: 20 },
      { id: 'out', name: 'OUT', type: 'digital', x: 0, y: 40 },
      { id: 'gnd', name: 'GND', type: 'ground', x: 0, y: 60 },
    ],
    defaultProps: { motion: false, label: 'PIR' },
  },
  {
    type: 'ir-sensor',
    label: 'IR Sensor',
    category: 'Sensors',
    description: 'Infrared sensor — detects proximity via reflected IR light.',
    width: 70,
    height: 70,
    keywords: ['ir', 'infrared', 'proximity', 'sensor', 'obstacle'],
    pins: [
      { id: 'vcc', name: 'VCC', type: 'power', x: 0, y: 20 },
      { id: 'out', name: 'OUT', type: 'digital', x: 0, y: 40 },
      { id: 'gnd', name: 'GND', type: 'ground', x: 0, y: 60 },
    ],
    defaultProps: { detected: false, label: 'IR' },
  },
  {
    type: 'battery',
    label: 'Battery 9V',
    category: 'Power',
    description: '9V battery — portable power source.',
    width: 80,
    height: 60,
    keywords: ['battery', 'power', '9v', 'supply', 'source'],
    pins: [
      { id: '+', name: '+', type: 'power', x: 0, y: 30 },
      { id: '-', name: '-', type: 'ground', x: 80, y: 30 },
    ],
    defaultProps: { voltage: 9, label: '9V' },
  },
  {
    type: 'power-5v',
    label: '5V Power',
    category: 'Power',
    description: '5V power source — provides a constant 5V supply.',
    width: 60,
    height: 40,
    keywords: ['5v', 'power', 'vcc', 'supply', 'source'],
    pins: [
      { id: '+', name: '+', type: 'power', x: 0, y: 20 },
      { id: '-', name: 'GND', type: 'ground', x: 60, y: 20 },
    ],
    defaultProps: { voltage: 5, label: '5V' },
  },
  {
    type: 'power-3v3',
    label: '3.3V Power',
    category: 'Power',
    description: '3.3V power source — provides a constant 3.3V supply.',
    width: 60,
    height: 40,
    keywords: ['3v3', '3.3v', 'power', 'vcc', 'supply'],
    pins: [
      { id: '+', name: '+', type: 'power', x: 0, y: 20 },
      { id: '-', name: 'GND', type: 'ground', x: 60, y: 20 },
    ],
    defaultProps: { voltage: 3.3, label: '3.3V' },
  },
  {
    type: 'gnd',
    label: 'GND',
    category: 'Power',
    description: 'Ground reference — 0V reference point for the circuit.',
    width: 50,
    height: 40,
    keywords: ['gnd', 'ground', 'earth', 'reference', '0v'],
    pins: [
      { id: 'g', name: 'GND', type: 'ground', x: 25, y: 0 },
    ],
    defaultProps: { label: 'GND' },
  },
  {
    type: 'and-gate',
    label: 'AND Gate',
    category: 'Logic',
    description: 'AND logic gate — output is HIGH only when both inputs are HIGH.',
    width: 80,
    height: 60,
    keywords: ['and', 'gate', 'logic', 'boolean'],
    pins: [
      { id: 'a', name: 'A', type: 'digital', x: 0, y: 15 },
      { id: 'b', name: 'B', type: 'digital', x: 0, y: 45 },
      { id: 'out', name: 'OUT', type: 'digital', x: 80, y: 30 },
    ],
    defaultProps: { label: 'AND' },
  },
  {
    type: 'or-gate',
    label: 'OR Gate',
    category: 'Logic',
    description: 'OR logic gate — output is HIGH when either input is HIGH.',
    width: 80,
    height: 60,
    keywords: ['or', 'gate', 'logic', 'boolean'],
    pins: [
      { id: 'a', name: 'A', type: 'digital', x: 0, y: 15 },
      { id: 'b', name: 'B', type: 'digital', x: 0, y: 45 },
      { id: 'out', name: 'OUT', type: 'digital', x: 80, y: 30 },
    ],
    defaultProps: { label: 'OR' },
  },
  {
    type: 'not-gate',
    label: 'NOT Gate',
    category: 'Logic',
    description: 'NOT logic gate — inverts the input signal.',
    width: 70,
    height: 40,
    keywords: ['not', 'gate', 'inverter', 'logic', 'boolean'],
    pins: [
      { id: 'a', name: 'A', type: 'digital', x: 0, y: 20 },
      { id: 'out', name: 'OUT', type: 'digital', x: 70, y: 20 },
    ],
    defaultProps: { label: 'NOT' },
  },
  {
    type: 'nand-gate',
    label: 'NAND Gate',
    category: 'Logic',
    description: 'NAND logic gate — NOT AND. Output is LOW only when both inputs are HIGH.',
    width: 80,
    height: 60,
    keywords: ['nand', 'gate', 'logic', 'boolean'],
    pins: [
      { id: 'a', name: 'A', type: 'digital', x: 0, y: 15 },
      { id: 'b', name: 'B', type: 'digital', x: 0, y: 45 },
      { id: 'out', name: 'OUT', type: 'digital', x: 80, y: 30 },
    ],
    defaultProps: { label: 'NAND' },
  },
  {
    type: 'nor-gate',
    label: 'NOR Gate',
    category: 'Logic',
    description: 'NOR logic gate — NOT OR. Output is HIGH only when both inputs are LOW.',
    width: 80,
    height: 60,
    keywords: ['nor', 'gate', 'logic', 'boolean'],
    pins: [
      { id: 'a', name: 'A', type: 'digital', x: 0, y: 15 },
      { id: 'b', name: 'B', type: 'digital', x: 0, y: 45 },
      { id: 'out', name: 'OUT', type: 'digital', x: 80, y: 30 },
    ],
    defaultProps: { label: 'NOR' },
  },
  {
    type: 'xor-gate',
    label: 'XOR Gate',
    category: 'Logic',
    description: 'XOR logic gate — output is HIGH when inputs differ.',
    width: 80,
    height: 60,
    keywords: ['xor', 'gate', 'logic', 'boolean', 'exclusive'],
    pins: [
      { id: 'a', name: 'A', type: 'digital', x: 0, y: 15 },
      { id: 'b', name: 'B', type: 'digital', x: 0, y: 45 },
      { id: 'out', name: 'OUT', type: 'digital', x: 80, y: 30 },
    ],
    defaultProps: { label: 'XOR' },
  },
  {
    type: 'breadboard',
    label: 'Breadboard',
    category: 'Prototyping',
    description: 'Half-size breadboard — 830 tie points for prototyping circuits.',
    width: 300,
    height: 120,
    keywords: ['breadboard', 'protoboard', 'prototype', 'solderless'],
    pins: [
      { id: 'r1a', name: 'A1', type: 'generic', x: 30, y: 30 },
      { id: 'r1b', name: 'E1', type: 'generic', x: 30, y: 50 },
      { id: 'r2a', name: 'F1', type: 'generic', x: 30, y: 70 },
      { id: 'r2b', name: 'J1', type: 'generic', x: 30, y: 90 },
    ],
    defaultProps: { label: 'Breadboard' },
  },
];

export const COMPONENT_MAP: Record<string, ComponentDefinition> = Object.fromEntries(
  COMPONENT_LIBRARY.map((c) => [c.type, c])
);

export const CATEGORIES = [...new Set(COMPONENT_LIBRARY.map((c) => c.category))];

export function searchComponents(query: string): ComponentDefinition[] {
  const q = query.toLowerCase().trim();
  if (!q) return COMPONENT_LIBRARY;
  return COMPONENT_LIBRARY.filter(
    (c) =>
      c.label.toLowerCase().includes(q) ||
      c.type.includes(q) ||
      c.category.toLowerCase().includes(q) ||
      c.keywords?.some((k) => k.includes(q))
  );
}
